name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd /var/www/management-app
        npm install

    - name: Build Angular App
      run: |
        cd /var/www/management-app
        npm run build --configuration=production

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}          # Your EC2 instance IP
        username: ubuntu                       # Default username for EC2 instances
        key: ${{ secrets.SSH_PRIVATE_KEY }}    # Private SSH key stored in GitHub secrets
        script: |
          # Navigate to the project directory
          cd /var/www/management-app
          
          # Step 1: Pull the latest changes from the main branch
          sudo git pull https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/blackfrankwhite/management-app.git main

          # Step 2: Install dependencies and build the project
          sudo npm install
          sudo npm run build --configuration=production

          # Step 3: Set ownership and permissions
          sudo chown -R www-data:www-data /var/www/management-app
          sudo chmod -R 775 /var/www/management-app

          # Step 4: Restart Nginx to serve the updated front-end
          sudo systemctl restart nginx
